### ISSUE TITLE
Выделение слова двойным щелчком

### ISSUE THREAD

**Issue by Roman-** [MikeMirzayanov/hat42-issue-tracking#4]
При двойном щелчке по слову из лога объяснённых слов происходит его выделение вместе с цифрами (секундами) из таймкода.
Двойной щелчок по слову часто используется игроками для его выделения с целью последующего поиска значения (правая кнопка мыши -> искать в Google) или просто копирования для вставки в нужную поисковую систему.
Было бы неплохо исправить это поведение, а ещё лучше - сразу давать возможность посмотреть значение.

**Comment by MikeMirzayanov** [comment]
Не могу воспроизвести. Возможно, раньше выглядело как-то по-другому. Сейчас по двойному клику выделяется слово между кавычками.

![image](https://github.com/MikeMirzayanov/hat42-issue-tracking/assets/1701892/22f39574-de90-4315-a113-0b4b79961d40)
